### ISSUE TITLE
🧹 [CHORE]: FE - CSS Reset Update

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1168]
### Summary

Now that FF supports balance and pretty wraps, add this.

```css
* {
  box-sizing: border-box; position: relative; min-width: 0;
｝
body {
  min-height: 100dvh;
}
p {
  text-wrap: pretty;
｝
h1, h2, h3, h4 {
  text-wrap: balance；
}
```

### Tasks

- [ ]
