### ISSUE TITLE
[FEAT] - content - add a workflow to ping search engines with sitemap changes

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#776]
- https://trevorfox.com/2018/09/ping-sitemaps-search-engines/

something along these lines:

```yaml
name: Ping Google about updated sitemap

on:
  push:
    branches: [ master ]

jobs:
  ping:
    name: Ping Google
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP GET request
        # Example: `curl http://www.google.com/ping?sitemap=https://www.example.com/sitemap.xml`
        run: curl http://www.google.com/ping?sitemap=FULL_URL_OF_YOUR/sitemap.xml
```
