### ISSUE TITLE
[FEAT] - frontend - add more motion-reducing specificity to CSS transition rules

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#799]
From https://www.a11yproject.com/posts/understanding-vestibular-disorders/

```css
@media (prefers-reduced-motion: reduce) {  
      *,  
      ::before,  
      ::after {  
        animation-duration: 0.001s !important;  
        animation-iteration-count: 1 !important;  
        transition-duration: 0.001s !important;  
      }  
    }
```
