### ISSUE TITLE
🐞 [BUG]: FE - Add View Transitions to Motion Mediaquery

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#876]
### CSS

```css
::view-transition-old(root),
::view-transition-new(root) {
  animation-duration: 0.0001s;
}
```

### Tasks

- [ ] add CSS to `transitions.css`
